#pragma once

#include <cstdint>

// Self-designed 5x7 monospace glyph set (space, - . : / ( ) %, 0-9, A-Z).
// Generated by scripts/gen_font.py - do not hand-edit the byte tables.
// Column-major: 5 bytes per glyph, bit0 = top row, bit6 = bottom row.
// Only uppercase + digits are defined: Dashboard.cpp uppercases all text
// before drawing, so lowercase glyphs are intentionally omitted.

namespace font5x7 {

constexpr uint8_t GLYPH_WIDTH = 5;
constexpr uint8_t GLYPH_HEIGHT = 7;

// Returns nullptr for characters outside the supported set; caller should
// fall back to a blank glyph (EinkCanvas::drawText skips them).
const uint8_t* glyphFor(char c);

}  // namespace font5x7

